[mainConfig]
appName = "GoMind"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "your authcode"
email = "your email"

[redisConfig]
host = "redis"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "mysql"
port = 3306
user = "root"
password = "123456"
databaseName = "GoMind"
charset = "utf8mb4"

[jwtConfig]
expire_duration = 8760
issuer = "huanheart"
subject = "GoMind"
key = "GoMind-v1"

[rabbitmqConfig]
host = "rabbitmq"
port = 5672
username = "root"
password = "123456"
vhost = "/"

[ragModelConfig]
embeddingType = "openai"
embeddingModel = "text-embedding-004"
chatModelName = "gemini-1.5-flash"
docDir = "./docs"
baseUrl = "https://generativelanguage.googleapis.com/v1beta/openai/"
dimension = 768

